# Generated by Django 4.2.6 on 2023-11-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guarderias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=200, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=25)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='guarderias')),
            ],
            options={
                'verbose_name': 'guarderia',
                'verbose_name_plural': 'guarderias',
            },
        ),
    ]
