# Generated by Django 4.2.6 on 2023-11-22 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_inicio', models.DateField()),
                ('f_fin', models.DateField()),
                ('guarderia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.guarderias')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
            },
        ),
    ]
