# Generated by Django 4.2.7 on 2023-11-25 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='guarderias',
            name='correoElec',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='guarderias',
            name='descrip',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='guarderias',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='guarderias',
            name='disponibilidad',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='reserva',
            name='descrip',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('Cancelado', 'Cancelado'), ('Rechazado', 'Rechazado'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_fin',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_inicio',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='mascota',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='responsable',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guarderias',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='guarderias/'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
